swagger: '2.0'
info:
  version: '1.0'
  title: 1Trial
  x-lastModified: '29 May 2020 2:04:47 pm (India Standard Time)'
paths:
  /asasa:
    post:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: postAsasa
    put:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
        '300':
          description: cdaa
          schema:
            type: string
      parameters: []
      operationId: putAsasa
      consumes: []
