consumes:
  - application/json
definitions:
  Hub:
    properties:
      callback:
        type: string
      query:
        type: string
    type: object
  Note:
    properties:
      author:
        type: string
      date:
        format: date-time
        type: string
      text:
        type: string
    type: object
  OrderItem:
    properties:
      action:
        type: string
      appointment:
        type: string
      billingAccount:
        items:
          $ref: '#/definitions/Reference'
        type: array
      id:
        type: string
      product:
        $ref: '#/definitions/Product'
      productOffering:
        $ref: '#/definitions/ProductOffering'
      state:
        enum:
          - Acknowledged
          - InProgress
          - Cancelled
          - Completed
          - Rejected
          - Pending
          - Held
          - Failed
          - Partial
        type: string
    type: object
  Product:
    properties:
      href:
        type: string
      id:
        type: string
      place:
        $ref: '#/definitions/Reference'
      productCharacteristic:
        items:
          $ref: '#/definitions/ProductCharacteristic'
        type: array
      productRelationship:
        items:
          $ref: '#/definitions/ProductRelationship'
        type: array
      relatedParty:
        items:
          $ref: '#/definitions/Reference'
        type: array
    type: object
  ProductCharacteristic:
    properties:
      name:
        type: string
      value:
        type: string
    type: object
  ProductOffering:
    properties:
      bundledProductOffering:
        items:
          $ref: '#/definitions/Reference'
        type: array
      href:
        type: string
      id:
        type: string
    type: object
  ProductOrder:
    properties:
      category:
        type: string
      completionDate:
        format: date-time
        type: string
      description:
        type: string
      expectedCompletionDate:
        format: date-time
        type: string
      externalId:
        type: string
      href:
        type: string
      id:
        format: int64
        type: integer
      note:
        items:
          $ref: '#/definitions/Note'
        type: array
      notificationContact:
        type: string
      orderDate:
        format: date-time
        type: string
      orderItem:
        items:
          $ref: '#/definitions/OrderItem'
        type: array
      priority:
        type: string
      relatedParty:
        items:
          $ref: '#/definitions/Reference'
        type: array
      requestedCompletionDate:
        format: date-time
        type: string
      requestedStartDate:
        format: date-time
        type: string
      state:
        enum:
          - Acknowledged
          - InProgress
          - Cancelled
          - Completed
          - Rejected
          - Pending
          - Held
          - Failed
          - Partial
        type: string
    type: object
  ProductOrderIn:
    properties:
      category:
        type: string
      completionDate:
        format: date-time
        type: string
      description:
        type: string
      expectedCompletionDate:
        format: date-time
        type: string
      externalId:
        type: string
      note:
        items:
          $ref: '#/definitions/Note'
        type: array
      notificationContact:
        type: string
      orderDate:
        format: date-time
        type: string
      priority:
        type: string
      relatedParty:
        items:
          $ref: '#/definitions/Reference'
        type: array
      requestedCompletionDate:
        format: date-time
        type: string
      requestedStartDate:
        format: date-time
        type: string
      state:
        enum:
          - Acknowledged
          - InProgress
          - Cancelled
          - Completed
          - Rejected
          - Pending
          - Held
          - Failed
          - Partial
        type: string
    type: object
  ProductRelationship:
    properties:
      product:
        $ref: '#/definitions/Product'
      type:
        enum:
          - reliesOn
          - bundled
          - targets
          - isTargeted
        type: string
    type: object
  Reference:
    properties:
      href:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  GiveNewSchemaNameHere:
    type: object
    properties:
      key1:
        type: string
        default: v1
      key2:
        type: string
        default: v2
host: env-0693795.jelastic.servint.net
info:
  description: ''
  title: BU_privateEndpoint
  version: '2.0'
  x-lastModified: '2020-08-18T08:14:38.000Z'
paths:
  /hub:
    get:
      deprecated: false
      description: ''
      operationId: hubFind
      responses:
        '200':
          description: List of Hub
          schema:
            type: array
            items:
              $ref: '#/definitions/GiveNewSchemaNameHere'
          examples:
            application/json:
              - key1: v1
                key2: v2
      summary: hubFind
      tags: []
      parameters: []
      produces:
        - application/json
    post:
      deprecated: false
      description: ''
      operationId: hubCreate
      parameters:
        - name: hub
          in: body
          schema:
            $ref: '#/definitions/Hub'
      responses:
        '201':
          description: Hub
          schema:
            $ref: '#/definitions/Hub'
      summary: hubCreate
      tags:
        - hub
      consumes:
        - application/json
  '/hub/{hubId}':
    delete:
      deprecated: false
      description: ''
      operationId: hubDelete
      parameters:
        - name: hubId
          in: path
          required: true
          type: string
          format: ''
      responses:
        '204':
          description: Success
      summary: hubDelete
      tags:
        - hub
    get:
      deprecated: false
      description: ''
      operationId: hubGet
      parameters:
        - name: hubId
          in: path
          required: true
          type: string
          format: ''
      responses:
        '200':
          description: Hub
          schema:
            $ref: '#/definitions/Hub'
      summary: hubGet
      tags:
        - hub
  /productOrder:
    get:
      deprecated: false
      description: ''
      operationId: productOrderFind
      parameters:
        - name: fields
          in: query
          description: ''
          required: false
          type: string
          format: ''
      responses:
        '200':
          description: List of ProductOrder
          schema:
            items:
              $ref: '#/definitions/ProductOrder'
            type: array
      summary: productOrderFind
      tags:
        - productOrder
    post:
      deprecated: false
      description: ''
      operationId: productOrderInCreate
      parameters:
        - name: productOrder
          in: body
          schema:
            $ref: '#/definitions/ProductOrderIn'
      responses:
        '201':
          description: ProductOrderIn
          schema:
            $ref: '#/definitions/ProductOrderIn'
      summary: productOrderInCreate
      tags:
        - productOrder
        - null
        - hub
      consumes:
        - application/json
      produces:
        - application/json
        - application/xml
  '/productOrder/{productOrderId}':
    get:
      deprecated: false
      description: ''
      operationId: productOrderGet
      parameters:
        - name: fields
          in: query
          description: ''
          required: false
          type: string
          format: ''
        - name: productOrderId
          in: path
          required: true
          type: string
          format: ''
      responses:
        '200':
          description: ProductOrder
          schema:
            $ref: '#/definitions/ProductOrder'
      summary: productOrderGet
      tags:
        - productOrder
    patch:
      deprecated: false
      description: ''
      operationId: productOrderPatch
      parameters:
        - name: productOrderId
          in: path
          required: true
          type: string
          format: ''
        - name: productOrder
          in: body
          schema:
            $ref: '#/definitions/ProductOrder'
      responses:
        '200':
          description: Success ProductOrder
          schema:
            $ref: '#/definitions/ProductOrder'
      summary: productOrderPatch
      tags:
        - productOrder
      consumes:
        - application/json
  /33:
    put:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: put33
      tags:
        - mudassaar
        - zss
        - xddd
        - null
        - sss
        - sdsds
        - sdesff
        - ddfdscs
        - sss
        - ads
produces:
  - application/json
schemes:
  - http
swagger: '2.0'
