{
  "swagger": "2.0",
  "info": {
    "version": "1.2",
    "title": "fff",
    "x-lastModified": "06 December 2019 4:59:15 pm (India Standard Time)"
  },
  "paths": {
    "/kk": {
      "get": {
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Success response"
          }
        },
        "parameters": [],
        "operationId": "getKk"
      },
      "post": {
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Success response"
          }
        },
        "parameters": [],
        "operationId": "postKk"
      },
      "put": {
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Success response"
          }
        },
        "parameters": [],
        "operationId": "putKk"
      },
      "patch": {
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Success response"
          }
        },
        "parameters": [],
        "operationId": "patchKk"
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Success response"
          }
        },
        "parameters": [],
        "operationId": "deleteKk"
      }
    }
  }
}