swagger: '2.0'
info:
  version: 1.0.0
  title: sample
  x-lastModified: '28 May 2020 4:19:33 pm (India Standard Time)'
paths:
  /sapmle:
    put:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
        '300':
          description: sample
      parameters: []
      operationId: putSapmle
      tags:
        - aasif
    delete:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: deleteSapmle
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: postSapmle
    post:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: patchSapmle
    patch:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: patchSapmleiyb
